name: Lint (Bun)

on:
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Bun.js
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0
      - run: bun install --frozen-lockfile
      - run: bun run build --if-present
      - run: bun lint
